export CC = $(TRIPLET)gcc
export AS = $(TRIPLET)as
export CXX = $(TRIPLET)g++
export LD = $(TRIPLET)ld
export AR = $(TRIPLET)ar
export RTOS_PATH
export RTOS_BUILD_DIR
export ARCH
export BOARD
export PREFIX
export COMPILE_RULES = $(RTOS_PATH)/make/Makefile.rules
